### ISSUE TITLE
Classes required to implement and extend Action are not exported

### ISSUE THREAD

**Issue by DanRoseus** [elyra-ai/canvas#1542]
Ref: 3650

The docs here:
https://github.com/elyra-ai/canvas/wiki/2.5-Command-Stack-API

Show an example of creating a new action:
```js
export default class CreateNodeAction extends Action {
```

But the `Action` base class is not exported.

I would also like to extend some of the existing actions rather than copying the code or rewriting them. I'm trying to override actions that act on links to also update some parameters in the source node for the link as part of the action, so want to override:
- CreateAutoNodeAction
- CreateNodeAction
- CreateNodeLinkAction
- DeleteObjectsAction
- DisconnectObjectsAction
- PasteAction

Could all of the above be exported?

**Comment by tomlyn** [comment]
Hi @DanRoseus 
I am a little worries about offering that capability through the API because it would probably restrict internal changes I could make in future to those actions. 

Have you investigated the `EditActionHandler` and even `BeforeEditActionHanlder` callbacks? They can be used to do make changes in additional to the default behavior of the actions. For example, before `CreateAutoNodeAction` is executed `BeforeEditActionHanlder` will be called and then after the action is completed `EditActionHandler` will be called. The parameters passed in for these calls can be used to differentiate what action was performed.

**Comment by DanRoseus** [comment]
@tomlyn , yes, I initially implemented it that way, but that doesn't support undo/redo. To support undo/redo the whole change needs to be made as a single transaction captured by the Action. For now I have temporarily copied those classes out into my own repo, but it would be better to import them from here.

**Comment by tomlyn** [comment]
Hi @DanRoseus Those calls do support undo / redo. 
For example, when the user performs an undo gesture they are called with  editType field of the first parameter set to "undo" and the second parameter set to the command that is being undone.

**Comment by tomlyn** [comment]
Hi @DanRoseus - Just checking back with you to see where we are with this. Did you look into the undo/redo support ?

**Comment by DanRoseus** [comment]
Hi @tomlyn , I can see that it's possible to do it that way. I would have to read through the code to work out what is contained in the undocumented command structure. I prefer to do this in an object oriented way and extend the existing actions, so for now I've made a copy of the command-actions and action.js and it's up and working using my extended classes.

**Comment by tomlyn** [comment]
Hi @DanRoseus -- Are you still interested in this requirement. I can go ahead and do it but just wanted to make sure you still need it.

**Comment by DanRoseus** [comment]
Hi @tomlyn , I am, yes. I have copied a number of files from Elyra Canvas in to our repo to work around this and it would be nice not to have to do that, so yes please!
