### ISSUE TITLE
Paste button is always enabled

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/canvas#167]
Ideally the paste button should be disabled when clipboard is empty.
Even though there is a listener for clipboard events in order to enable/disable paste button, even when there is no event on the clipboard the button is always enabled. The same behavior is noticed when we manually set its property `enable:false` to paste action in `toolbarConfig` when rendering canvas.

This is an example of a pipeline editor in elyra using canvas when there are no clipboard event (we intentionally enable `save` and `add comments` buttons on empty pipelines):
![image](https://user-images.githubusercontent.com/25207344/87827136-3a53ea80-c848-11ea-96e7-bc7c202e8041.png)

The code where paste state is set and button enabled/disabled:
https://github.com/elyra-ai/canvas/blob/b596b3c9c864331385921871935564a608671caa/canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx#L394-L396

https://github.com/elyra-ai/canvas/blob/b596b3c9c864331385921871935564a608671caa/canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx#L412-L414

Original issue opened in [Elyra](https://github.com/elyra-ai/elyra/issues/768)

**Comment by tomlyn** [comment]
This behavior occurs because common-canvas uses its own internal clipboard rather than the operating system clipboard. The common-canvas objects are copied/cut to and pasted from a clipboard that resides in local storage in the web browser. So in actual fact there probably is something on the internal 'clipboard' in the case you are seeing and clicking paste would add it to your canvas. 

I realize this is not an ideal implementation. It was implemented a long time ago. Common-canvas should be using the operating system clipboard. I looked into doing that recently but got distracted by more important issues.
