### ISSUE TITLE
Base Action class needed to extend functionality is not exported

### ISSUE THREAD

**Issue by jeesonjohnson** [elyra-ai/canvas#1719]
Please refer to original issue: https://github.com/elyra-ai/canvas/issues/1542

As stated in the issue above, to extend the functionality of default actions, it is useful to have access to the `Action` class. As documented [here](https://github.com/elyra-ai/canvas/wiki/2.5-Command-Stack-API). However the default base `Action` class is NOT exported. This issue is to try and request the `Action` class to also be exported.

I think the related [PR](https://github.com/elyra-ai/canvas/pull/1697/files#diff-d62554a3568352f69b79cd968d68adf45868c552de7db1b27c63401cf9175431R33) may have missed exporting the `Action` class as requested in the original issue.

**Comment by tomlyn** [comment]
Hi -- It made sense to export the 6 requested Action classes from common canvas because sub-classes of them will inherit the functionality they implement. However, the [Action class](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/common-canvas/src/command-stack/action.js) itself doesn't have any function and is really just like an interface class (That is, it just describes what an action class should look like.)  This is all it contains:

```
class Action {

	do() {
	}

	undo() {
	}

	redo() {
	}

	getLabel() {
	}
}
```   
As long as any action class you write implements the four methods it can be added to the command stack and will be handled successfully.    I can export it if you like but extending from it is not going to add anything.

**Comment by jeesonjohnson** [comment]
Hi @tomlyn, as you suggested we currently implement the Action class within our codebase and implement the methods you described, and modify it accordingly to work with our code. This is more of a stylistic suggestion. But we think it is beneficial to export the Action class for two main reasons:
1) Makes it easier to interact with the Canvas API, as you can just rely on the exported classes rather than having to re-define the same class again within our codebase. 
2) Helps against future proofing, as if the underlying Action class is added to, we can be sure that a consumer's codebase will be inline with the interfaces provided by elyra-ai.

**Comment by jeesonjohnson** [comment]
After further discussion internally, i take what i mentioned back! Thanks @tomlyn.
