### ISSUE TITLE
Multiple tabs - UI data does not refresh when switched

### ISSUE THREAD

**Issue by tanvimehta10** [elyra-ai/canvas#1940]
https://ibm-analytics.slack.com/archives/C598XEX8S/p1713987591343319 

Link to slack conversation. Since it was reproducible on your end and the carbon changes will have to be applied on ELyra code assigning it to Elyra team

**Comment by nmgokhale** [comment]
@tanvimehta10 This is not an elyra issue. This is an issue in Carbon 11 because common-properties is passing `multiselectDropdown.selectedOptions = []` empty array as expected. Also I can see `None selected` text in the multiselect control which means common-properties is passing an empty array.

You can follow up with Carbon 11 team to get it fixed.

> Carbon changes will have to be applied on ELyra code assigning it to Elyra team

We don't need any code change in elyra canvas other than bumping up carbon 11 version after they fix the issue. This is automatically done right now, [as soon as new carbon minor version is available, elyra will pickup the latest version](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/common-canvas/package.json#L62).

Closing this issue.

CC: @JesusGuerrero @matthoward366
