### ISSUE TITLE
Improve Undo / Redo tooltips -- excude 0 <objects> from the text 

### ISSUE THREAD

**Issue by nabilIbm** [elyra-ai/canvas#951]
Ref: 3268

[[](https://media.github.ibm.com/user/17025/files/221dbb00-7885-11ec-951f-f1abaa01110e)image](https://media.github.ibm.com/user/17025/files/221dbb00-7885-11ec-951f-f1abaa01110e)
If there are 0 objects, then just exclude that from the tooltip IMO. Rather than saying "0 comments" -- just leave that part out. Same would apply if there were 0 nodes or 0 links.

**Comment by tomlyn** [comment]
Here's a little more detail on what needs to be done. The text of the message that is displayed for a delete action needs to vary depending on what objects are being deleted. So instead of saying something like this:
```
Delete 0 nodes, 2 comments and 1 links
```
it should say:
```
Delete 2 comments and 1 links
```
or, say, if only nodes were deleted it would say:
```
Delete 4 nodes
```
We should not try to construct English sentences programmatically because this can cause translation problems. This means we need a series of messages for the different combinations of objects that might be deleted.
1. Just nodes
2. Just comments
3. Just links
4. Node and comments (we already have a message for this)
5. Nodes and links
6. Nodes comments and links (we already have a message for this)
7. Comments and links

**Comment by tomlyn** [comment]
Fixed
